### ISSUE TITLE
pretty_dt breaks in case of "Time difference of NA secs"

### ISSUE THREAD

**Issue by petermeissner** [gaborcsardi/prettyunits#9]
Consider the following example below. 

While `difftime()` considers it valid to have `NA` time differences, `pretty_dt()` does break with a rather ominous error message.

- It would be great to have `pretty_dt()` just return "NA" and not error out.
- If this is not possible it would be great to have at least a more informative error message that hints at where and why the problem is occurring (e.g. "pretty_dt: Sorry, do not know how to handle NA difftimes.")

```r
difftime(NA,NA)
## Time difference of NA secs

pretty_dt(difftime(NA,NA))
## Error in if (pieces[1]) pieces[1] %+% "d " else "" : 
##   argument is not interpretable as logical
```

**Comment by gaborcsardi** [comment]
Agreed, it should return `NA_character_`. PR is welcome. :)

**Comment by petermeissner** [comment]
I go look if I can find one ... :-)
